export const susuCircleAbi = [
  {
    type: "function",
    name: "getCircle",
    stateMutability: "view",
    inputs: [{ name: "circleId", type: "uint256" }],
    outputs: [
      { name: "creator", type: "address" },
      { name: "contributionAmount", type: "uint256" },
      { name: "totalRounds", type: "uint256" },
      { name: "roundInterval", type: "uint256" },
      { name: "currentRound", type: "uint256" },
      { name: "roundStartTime", type: "uint256" },
      { name: "paidCount", type: "uint256" },
      { name: "status", type: "uint8" },
      { name: "participantCount", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "getParticipants",
    stateMutability: "view",
    inputs: [{ name: "circleId", type: "uint256" }],
    outputs: [{ name: "", type: "address[]" }],
  },
  {
    type: "function",
    name: "getCurrentRecipient",
    stateMutability: "view",
    inputs: [{ name: "circleId", type: "uint256" }],
    outputs: [{ name: "recipient", type: "address" }],
  },
  {
    type: "function",
    name: "hasPaidRound",
    stateMutability: "view",
    inputs: [
      { name: "circleId", type: "uint256" },
      { name: "round", type: "uint256" },
      { name: "participant", type: "address" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "isParticipant",
    stateMutability: "view",
    inputs: [
      { name: "circleId", type: "uint256" },
      { name: "participant", type: "address" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "nextCircleId",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "createCircle",
    stateMutability: "nonpayable",
    inputs: [
      { name: "contributionAmount", type: "uint256" },
      { name: "totalRounds", type: "uint256" },
      { name: "roundInterval", type: "uint256" },
    ],
    outputs: [{ name: "circleId", type: "uint256" }],
  },
  {
    type: "function",
    name: "joinCircle",
    stateMutability: "nonpayable",
    inputs: [{ name: "circleId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "startCircle",
    stateMutability: "nonpayable",
    inputs: [{ name: "circleId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "depositRoundFunds",
    stateMutability: "payable",
    inputs: [{ name: "circleId", type: "uint256" }],
    outputs: [],
  },
] as const;
